name: CI
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install uv
        run: |
          UV_VERSION=0.6.14
          curl -sSL "https://github.com/astral-sh/uv/releases/download/v${UV_VERSION}/uv-linux-amd64" -o uv
          curl -sSL "https://github.com/astral-sh/uv/releases/download/v${UV_VERSION}/uvx-linux-amd64" -o uvx
          chmod +x uv uvx
          sudo mv uv uvx /usr/local/bin/

      - name: Sync dependencies
        run: uv sync --frozen

      - name: Run tests
        run: uv run python -m unittest discover